// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLKDGBfz_TAK_Clkmz0v6kkCNJ_EaQKo',
    appId: '1:173328285943:web:e4cea3e096583a0ee5d3f2',
    messagingSenderId: '173328285943',
    projectId: 'jetblack-saas',
    authDomain: 'jetblack-saas.firebaseapp.com',
    storageBucket: 'jetblack-saas.firebasestorage.app',
    measurementId: 'G-HW13FFK1VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0739G28yzmu_eSHGbywigZXTAuBZu9Cw',
    appId: '1:173328285943:android:f8a6afaf78ed38a2e5d3f2',
    messagingSenderId: '173328285943',
    projectId: 'jetblack-saas',
    storageBucket: 'jetblack-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCty8kOndKTiZfwZHKII4p2kpySUCxqc8o',
    appId: '1:173328285943:ios:a0373dfacf99e3b6e5d3f2',
    messagingSenderId: '173328285943',
    projectId: 'jetblack-saas',
    storageBucket: 'jetblack-saas.firebasestorage.app',
    iosBundleId: 'com.example.jetblackSaas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCty8kOndKTiZfwZHKII4p2kpySUCxqc8o',
    appId: '1:173328285943:ios:a0373dfacf99e3b6e5d3f2',
    messagingSenderId: '173328285943',
    projectId: 'jetblack-saas',
    storageBucket: 'jetblack-saas.firebasestorage.app',
    iosBundleId: 'com.example.jetblackSaas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfLKDGBfz_TAK_Clkmz0v6kkCNJ_EaQKo',
    appId: '1:173328285943:web:d93e89f983c65cb2e5d3f2',
    messagingSenderId: '173328285943',
    projectId: 'jetblack-saas',
    authDomain: 'jetblack-saas.firebaseapp.com',
    storageBucket: 'jetblack-saas.firebasestorage.app',
    measurementId: 'G-RZ4H044S32',
  );
}
